/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — process is alive.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe — checks more than DB connectivity.
         *
         *     Returns 200 only when:
         *       1. DB connection works (SELECT 1).
         *       2. Alembic version matches the latest expected revision (catches partial
         *          deploys where the schema is mid-migration).
         *       3. The audit trigger function exists in the `audit` schema (catches
         *          scenarios where the trigger was dropped — a HIPAA-relevant silent
         *          failure mode).
         *       4. There's at least one site row (the dashboard would render blank
         *          without seeded data; in fresh deploys the operator runs scripts/
         *          seed_sites.py before flipping the App Service to live traffic).
         *
         *     Returns 503 with a per-check breakdown otherwise. Cheap query cost
         *     (~3 SELECTs) — runs on every App Service health probe, no big deal.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sites
         * @description List all sites. Any authenticated role can read.
         */
        get: operations["list_sites_api_v1_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operations Summary */
        get: operations["operations_summary_api_v1_operations_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/sites-today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sites Today */
        get: operations["sites_today_api_v1_operations_sites_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Site Detail
         * @description Per-facility detail: today's row + 14-day history + entered_today flag.
         */
        get: operations["site_detail_api_v1_operations_sites__site_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finance/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finance Today */
        get: operations["finance_today_api_v1_finance_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finance/ar-aging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ar Aging */
        get: operations["ar_aging_api_v1_finance_ar_aging_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finance/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finance Kpis */
        get: operations["finance_kpis_api_v1_finance_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/finance/monthly-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly Trend */
        get: operations["monthly_trend_api_v1_finance_monthly_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinical/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clinical Summary */
        get: operations["clinical_summary_api_v1_clinical_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clinical/credentials-expiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credentials Expiring */
        get: operations["credentials_expiring_api_v1_clinical_credentials_expiring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People Summary */
        get: operations["people_summary_api_v1_people_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/open-positions-by-site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Positions By Site */
        get: operations["open_positions_by_site_api_v1_people_open_positions_by_site_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scorecards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scorecards
         * @description Exec-visible scorecard list. Doctors never see themselves.
         *
         *     The qualitative `mgma_band` is visible to anyone authenticated. The
         *     dollar-amount comp fields (`effective_comp_usd`, `fmv_source_note`)
         *     are only populated for callers with the `comp_viewer` role
         *     (CEO, CFO, admin); for everyone else those fields are null and the
         *     UI redacts them.
         */
        get: operations["list_scorecards_api_v1_scorecards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Alerts */
        get: operations["current_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Data-source + freshness info (no auth required).
         */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recent Uploads
         * @description List recent uploads. Any authenticated user can see (no PHI in rows).
         */
        get: operations["list_recent_uploads_api_v1_uploads_get"];
        put?: never;
        /** Stage Upload */
        post: operations["stage_upload_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/daily-census": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily Census
         * @description Return one row per site for the given date, with census=null where no entry exists.
         *
         *     Stable sort by site name so the UI row order is consistent across reloads.
         */
        get: operations["get_daily_census_api_v1_entries_daily_census_get"];
        put?: never;
        /**
         * Save Daily Census
         * @description Upsert all rows in the batch. One commit at the end → one audit txn.
         */
        post: operations["save_daily_census_api_v1_entries_daily_census_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/monthly-finance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monthly Finance
         * @description Return rows for a given (year, month). Defaults to the most recent
         *     completed month so the form pre-fills sensible values.
         */
        get: operations["get_monthly_finance_api_v1_entries_monthly_finance_get"];
        put?: never;
        /**
         * Save Monthly Finance
         * @description Upsert each (year, month, state) row in the batch.
         */
        post: operations["save_monthly_finance_api_v1_entries_monthly_finance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/weekly-clinical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weekly Clinical
         * @description Return both states' rows for a given week_ending. Defaults to last Sunday.
         */
        get: operations["get_weekly_clinical_api_v1_entries_weekly_clinical_get"];
        put?: never;
        /**
         * Save Weekly Clinical
         * @description Upsert each (week_ending, state) row in the batch.
         */
        post: operations["save_weekly_clinical_api_v1_entries_weekly_clinical_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/weekly-hr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weekly Hr
         * @description Return the row for a given week_ending. Defaults to last Sunday.
         *
         *     Returns null if no entry exists yet for that week — the form treats null
         *     as a fresh form.
         */
        get: operations["get_weekly_hr_api_v1_entries_weekly_hr_get"];
        put?: never;
        /**
         * Save Weekly Hr
         * @description Upsert one (week_ending) row.
         */
        post: operations["save_weekly_hr_api_v1_entries_weekly_hr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/census-portal/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials, issue a fresh session token, set the cookie.
         *
         *     Single-session lock: the new token overwrites any prior token, so a
         *     second simultaneous login boots the first browser on its next request.
         */
        post: operations["login_api_v1_census_portal_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/census-portal/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sites With Today
         * @description Return the same prefill payload as /login so the entry page can render
         *     after a refresh without re-authenticating.
         *
         *     Returns ONLY facility names + today's already-entered numbers. No
         *     operational data (no scorecards, finance, clinical, etc.) — keeps the
         *     portal's read surface narrow and predictable.
         */
        get: operations["list_sites_with_today_api_v1_census_portal_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/census-portal/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the active session token and the cookie.
         */
        post: operations["logout_api_v1_census_portal_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/census-portal/daily-census": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Daily Census
         * @description Bulk upsert today's census for the supplied site rows.
         *
         *     Same idempotent (site_id, entry_date) upsert as the dashboard's
         *     /entries/daily-census endpoint — but tagged with source='manual_portal'
         *     and entered_by_upn='census-portal@hhamedicine.com' for audit clarity.
         */
        post: operations["save_daily_census_api_v1_census_portal_daily_census_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Id */
            id: string;
            /** Severity */
            severity: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Owner */
            owner: string;
        };
        /** ArAging */
        ArAging: {
            /** Fl Total Usd */
            fl_total_usd: number;
            fl_buckets: components["schemas"]["ArBuckets"];
            /** Fl Over 120 Pct */
            fl_over_120_pct: number;
            /** Fl Source System */
            fl_source_system: string;
            /** Tx Total Usd */
            tx_total_usd: number;
            tx_buckets: components["schemas"]["ArBuckets"];
            /** Tx Over 120 Pct */
            tx_over_120_pct: number;
            /** Tx Source System */
            tx_source_system: string;
        };
        /** ArBuckets */
        ArBuckets: {
            /** Bucket 0 30 */
            bucket_0_30: number;
            /** Bucket 31 60 */
            bucket_31_60: number;
            /** Bucket 61 90 */
            bucket_61_90: number;
            /** Bucket 91 120 */
            bucket_91_120: number;
            /** Bucket Over 120 */
            bucket_over_120: number;
        };
        /** Body_stage_upload_api_v1_uploads_post */
        Body_stage_upload_api_v1_uploads_post: {
            /**
             * File
             * @description The PDF / XLSX / CSV to upload
             */
            file: string;
            /** @description Categorization — routes to the right extractor */
            file_type: components["schemas"]["FileType"];
        };
        /** ClinicalSummary */
        ClinicalSummary: {
            /** Hp 24H Pct */
            hp_24h_pct: number;
            /** Hp 24H Target */
            hp_24h_target: number;
            /** Dc 48H Pct */
            dc_48h_pct: number;
            /** Dc 48H Target */
            dc_48h_target: number;
            /** Los Fl Days */
            los_fl_days: number;
            /** Los Tx Days */
            los_tx_days: number;
            /** Los Woodmont Watch Days */
            los_woodmont_watch_days: number;
            /** Los Woodmont Trend Days */
            los_woodmont_trend_days: number;
            /** Credentials Expiring 30D */
            credentials_expiring_30d: number;
            /** Credentials Expiring 60D */
            credentials_expiring_60d: number;
            /** Credentials Expiring 90D */
            credentials_expiring_90d: number;
        };
        /** CredentialExpiring */
        CredentialExpiring: {
            /** Physician */
            physician: string;
            /** Type */
            type: string;
            /** Expires In Days */
            expires_in_days: number;
            /** Expires On */
            expires_on: string;
            /** Tier */
            tier: string;
        };
        /**
         * DailyCensusBatchIn
         * @description Full batch for a given date — up to 11 rows, one per site.
         */
        DailyCensusBatchIn: {
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Rows */
            rows: components["schemas"]["DailyEntryIn"][];
        };
        /**
         * DailyEntryHistoryRow
         * @description One past entry for a site — read-only on the detail page.
         */
        DailyEntryHistoryRow: {
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Census */
            census: number;
            /** Open Shifts */
            open_shifts: number;
            /** Entered By Upn */
            entered_by_upn: string;
            /** Source */
            source: string;
            /** Notes */
            notes: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * DailyEntryIn
         * @description One site's census for a given date, coming from the UI.
         */
        DailyEntryIn: {
            /**
             * Site Id
             * @description masters.sites.id
             */
            site_id: number;
            /**
             * Census
             * @description Patient count for the day
             */
            census: number;
            /**
             * Open Shifts
             * @description Unfilled provider shifts
             * @default 0
             */
            open_shifts: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * DailyEntryOut
         * @description One row for the daily-census page — joined with site name/state for display.
         *
         *     `census` is `None` for sites with no entry for the requested date, so the
         *     form can render a blank input instead of showing zero.
         */
        DailyEntryOut: {
            /** Site Id */
            site_id: number;
            /** Site Name */
            site_name: string;
            /** State */
            state: string;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Census */
            census: number | null;
            /** Open Shifts */
            open_shifts: number;
            /** Entered By Upn */
            entered_by_upn: string | null;
            /** Source */
            source: string | null;
            /** Notes */
            notes: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * FileType
         * @enum {string}
         */
        FileType: "census_pdf" | "finance_xlsx" | "clinical_xlsx" | "hr_xlsx" | "unknown";
        /** FinanceKpis */
        FinanceKpis: {
            /** Fl Days In Ar */
            fl_days_in_ar: number;
            /** Tx Days In Ar */
            tx_days_in_ar: number;
            /** Days In Ar Target */
            days_in_ar_target: number;
            /** Fl Ncr Pct */
            fl_ncr_pct: number;
            /** Tx Ncr Pct */
            tx_ncr_pct: number;
            /** Ncr Billed At */
            ncr_billed_at: string;
        };
        /** FinanceToday */
        FinanceToday: {
            /** Fl Daily Actual */
            fl_daily_actual: number;
            /** Fl Daily Target */
            fl_daily_target: number;
            /** Fl Daily Delta */
            fl_daily_delta: number;
            /** Fl Source System */
            fl_source_system: string;
            /** Tx Daily Actual */
            tx_daily_actual: number;
            /** Tx Daily Target */
            tx_daily_target: number;
            /** Tx Daily Delta */
            tx_daily_delta: number;
            /** Tx Source System */
            tx_source_system: string;
            /** Fl Mtd Actual */
            fl_mtd_actual: number;
            /** Fl Mtd Target */
            fl_mtd_target: number;
            /** Fl Mtd Pct */
            fl_mtd_pct: number;
            /** Ventra Fee Mtd */
            ventra_fee_mtd: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginIn
         * @description Email + password from the portal login form.
         */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Meta */
        Meta: {
            /** Generated At */
            generated_at: string;
            /** Data Source */
            data_source: string;
            /** Note */
            note: string;
        };
        /** MonthRevenue */
        MonthRevenue: {
            /** Month */
            month: string;
            /** Revenue Usd */
            revenue_usd: number;
        };
        /**
         * MonthlyFinanceBatchIn
         * @description Sandy submits one batch per month covering FL and/or TX.
         */
        MonthlyFinanceBatchIn: {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Rows */
            rows: components["schemas"]["MonthlyFinanceRowIn"][];
        };
        /**
         * MonthlyFinanceRowIn
         * @description One state's row inside a batch.
         */
        MonthlyFinanceRowIn: {
            state: components["schemas"]["StateCode"];
            /** Collections Usd */
            collections_usd: number | string;
            /**
             * Ventra Fee Usd
             * @default 0
             */
            ventra_fee_usd: number | string;
            /** Ar Total Usd */
            ar_total_usd: number | string;
            /**
             * Ar 0 30 Usd
             * @default 0
             */
            ar_0_30_usd: number | string;
            /**
             * Ar 31 60 Usd
             * @default 0
             */
            ar_31_60_usd: number | string;
            /**
             * Ar 61 90 Usd
             * @default 0
             */
            ar_61_90_usd: number | string;
            /**
             * Ar 91 120 Usd
             * @default 0
             */
            ar_91_120_usd: number | string;
            /**
             * Ar Over 120 Usd
             * @default 0
             */
            ar_over_120_usd: number | string;
            /** Net Collection Rate Pct */
            net_collection_rate_pct: number | string;
            /** Days In Ar */
            days_in_ar: number | string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * MonthlyFinanceRowOut
         * @description One persisted row, returned by GET + after-POST.
         */
        MonthlyFinanceRowOut: {
            /** Id */
            id: number;
            /** Year */
            year: number;
            /** Month */
            month: number;
            /**
             * Period First
             * Format: date
             */
            period_first: string;
            /** State */
            state: string;
            /** Collections Usd */
            collections_usd: string;
            /** Ventra Fee Usd */
            ventra_fee_usd: string;
            /** Ar Total Usd */
            ar_total_usd: string;
            /** Ar 0 30 Usd */
            ar_0_30_usd: string;
            /** Ar 31 60 Usd */
            ar_31_60_usd: string;
            /** Ar 61 90 Usd */
            ar_61_90_usd: string;
            /** Ar 91 120 Usd */
            ar_91_120_usd: string;
            /** Ar Over 120 Usd */
            ar_over_120_usd: string;
            /** Net Collection Rate Pct */
            net_collection_rate_pct: string;
            /** Days In Ar */
            days_in_ar: string;
            /** Source System */
            source_system: string;
            /** Entered By Upn */
            entered_by_upn: string;
            /** Notes */
            notes: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OpenPositionBySite */
        OpenPositionBySite: {
            /** Site */
            site: string;
            /** State */
            state: string;
            /** Count */
            count: number;
            /** Severity */
            severity: string;
        };
        /** OperationsSummary */
        OperationsSummary: {
            /** Total Fl Census */
            total_fl_census: number;
            /** Total Tx Census */
            total_tx_census: number;
            /** Total Fl 3Mo Avg */
            total_fl_3mo_avg: number;
            /** Census Variance Vs Avg */
            census_variance_vs_avg: number;
            /** Sites Below Avg */
            sites_below_avg: number;
            /** Open Shifts Total */
            open_shifts_total: number;
            /** Fl Site Count */
            fl_site_count: number;
            /** Tx Site Count */
            tx_site_count: number;
        };
        /** PeopleSummary */
        PeopleSummary: {
            /** Headcount W2 */
            headcount_w2: number;
            /** Headcount 1099 */
            headcount_1099: number;
            /** Headcount Total */
            headcount_total: number;
            /** Open Positions Total */
            open_positions_total: number;
            /** Turnover 90D Pct */
            turnover_90d_pct: number;
            /** Below Fmv Count */
            below_fmv_count: number;
        };
        /**
         * PortalCensusBatchIn
         * @description Whole-page save: today's count for all 11 sites in one POST.
         */
        PortalCensusBatchIn: {
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Rows */
            rows: components["schemas"]["PortalCensusRow"][];
        };
        /**
         * PortalCensusOut
         * @description One persisted row, mirrored back to the client.
         */
        PortalCensusOut: {
            /** Site Id */
            site_id: number;
            /** Site Name */
            site_name: string;
            /** State */
            state: string;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Census */
            census: number;
            /** Open Shifts */
            open_shifts: number;
            /** Source */
            source: string;
        };
        /**
         * PortalCensusRow
         * @description One row of the bulk save.
         */
        PortalCensusRow: {
            /** Site Id */
            site_id: number;
            /** Census */
            census: number;
            /**
             * Open Shifts
             * @default 0
             */
            open_shifts: number;
        };
        /**
         * PortalLoginOut
         * @description Login success — returns the prefill list so the form can render
         *     immediately without a second round-trip.
         */
        PortalLoginOut: {
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Sites */
            sites: components["schemas"]["PortalSiteOut"][];
        };
        /**
         * PortalSiteOut
         * @description One facility row, prefilled with today's existing census (or null).
         */
        PortalSiteOut: {
            /** Site Id */
            site_id: number;
            /** Site Name */
            site_name: string;
            /** State */
            state: string;
            /** Census */
            census: number | null;
            /** Open Shifts */
            open_shifts: number;
        };
        /** ScorecardOut */
        ScorecardOut: {
            /** Physician Id */
            physician_id: number;
            /** Name */
            name: string;
            /** Site */
            site: string;
            /** State */
            state: string;
            /** Employment Type */
            employment_type: string;
            /** Comp Model */
            comp_model: string;
            /** Status */
            status: string;
            /** Rank */
            rank: number;
            /** Rvu 90D */
            rvu_90d: number;
            /** Below Fmv */
            below_fmv: boolean;
            /**
             * Mgma Band
             * @enum {string}
             */
            mgma_band: "below_25" | "25_50" | "50_75" | "75_90" | "above_90";
            /** Mgma P50 Usd */
            mgma_p50_usd: number;
            /** Effective Comp Usd */
            effective_comp_usd?: number | null;
            /** Fmv Source Note */
            fmv_source_note?: string | null;
            /** Revenue Per Fte Usd */
            revenue_per_fte_usd?: number | null;
            /** Encounters Per Day */
            encounters_per_day?: number | null;
            /** Documentation Score Pct */
            documentation_score_pct?: number | null;
            /** Chart Turnaround Days */
            chart_turnaround_days?: number | null;
        };
        /**
         * SiteDetail
         * @description Per-facility drill-down: today's row + recent history + entered-today flag.
         */
        SiteDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Medical Director */
            medical_director: string | null;
            /** Md Status */
            md_status: string;
            /** Liaison */
            liaison: string | null;
            /** Census Today */
            census_today: number;
            /** Census 3Mo Avg */
            census_3mo_avg: number;
            /** Mtd Avg */
            mtd_avg: number;
            /** Variance Pct */
            variance_pct: number;
            /** Open Shifts */
            open_shifts: number;
            /** Contract End */
            contract_end: string;
            /** Annual Subsidy Usd */
            annual_subsidy_usd: number;
            /** Entered Today */
            entered_today: boolean;
            /** Recent Entries */
            recent_entries: components["schemas"]["DailyEntryHistoryRow"][];
        };
        /** SiteOut */
        SiteOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Hospital System */
            hospital_system: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SiteToday */
        SiteToday: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Medical Director */
            medical_director: string | null;
            /** Md Status */
            md_status: string;
            /** Liaison */
            liaison: string | null;
            /** Census Today */
            census_today: number;
            /** Census 3Mo Avg */
            census_3mo_avg: number;
            /** Mtd Avg */
            mtd_avg: number;
            /** Variance Pct */
            variance_pct: number;
            /** Open Shifts */
            open_shifts: number;
            /** Contract End */
            contract_end: string;
            /** Annual Subsidy Usd */
            annual_subsidy_usd: number;
        };
        /**
         * StateCode
         * @enum {string}
         */
        StateCode: "FL" | "TX";
        /**
         * UploadAcceptedOut
         * @description Response when a file is successfully uploaded + queued.
         */
        UploadAcceptedOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /** File Type */
            file_type: string;
            /**
             * Message
             * @default Upload accepted. Will be processed within 15 minutes.
             */
            message: string;
        };
        /** UploadOut */
        UploadOut: {
            /** Id */
            id: number;
            /** Uploaded By Upn */
            uploaded_by_upn: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** File Type */
            file_type: string;
            /** Original Filename */
            original_filename: string;
            /** Blob Name */
            blob_name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
            /** Processing Started At */
            processing_started_at: string | null;
            /** Processing Finished At */
            processing_finished_at: string | null;
            /** Rows Written */
            rows_written: number | null;
            /** Error Message */
            error_message: string | null;
            /** Retry Count */
            retry_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyClinicalBatchIn */
        WeeklyClinicalBatchIn: {
            /**
             * Week Ending
             * Format: date
             */
            week_ending: string;
            /** Rows */
            rows: components["schemas"]["WeeklyClinicalRowIn"][];
        };
        /**
         * WeeklyClinicalRowIn
         * @description One state's clinical row inside a weekly batch.
         */
        WeeklyClinicalRowIn: {
            state: components["schemas"]["StateCode"];
            /** Hp 24H Pct */
            hp_24h_pct: number | string;
            /** Dc 48H Pct */
            dc_48h_pct: number | string;
            /** Avg Los Days */
            avg_los_days: number | string;
            /**
             * Charts Audited Count
             * @default 0
             */
            charts_audited_count: number;
            /** Notes */
            notes?: string | null;
        };
        /** WeeklyClinicalRowOut */
        WeeklyClinicalRowOut: {
            /** Id */
            id: number;
            /**
             * Week Ending
             * Format: date
             */
            week_ending: string;
            /** State */
            state: string;
            /** Hp 24H Pct */
            hp_24h_pct: string;
            /** Dc 48H Pct */
            dc_48h_pct: string;
            /** Avg Los Days */
            avg_los_days: string;
            /** Charts Audited Count */
            charts_audited_count: number;
            /** Notes */
            notes: string | null;
            /** Entered By Upn */
            entered_by_upn: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WeeklyHrIn */
        WeeklyHrIn: {
            /**
             * Week Ending
             * Format: date
             */
            week_ending: string;
            /** Headcount W2 */
            headcount_w2: number;
            /** Headcount 1099 */
            headcount_1099: number;
            /**
             * Open Positions Total
             * @default 0
             */
            open_positions_total: number;
            /**
             * Terminations 90D Count
             * @default 0
             */
            terminations_90d_count: number;
            /**
             * Below Fmv Count
             * @default 0
             */
            below_fmv_count: number;
            /** Notes */
            notes?: string | null;
        };
        /** WeeklyHrOut */
        WeeklyHrOut: {
            /** Id */
            id: number;
            /**
             * Week Ending
             * Format: date
             */
            week_ending: string;
            /** Headcount W2 */
            headcount_w2: number;
            /** Headcount 1099 */
            headcount_1099: number;
            /** Open Positions Total */
            open_positions_total: number;
            /** Terminations 90D Count */
            terminations_90d_count: number;
            /** Below Fmv Count */
            below_fmv_count: number;
            /** Notes */
            notes: string | null;
            /** Entered By Upn */
            entered_by_upn: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sites_api_v1_sites_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operations_summary_api_v1_operations_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sites_today_api_v1_operations_sites_today_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteToday"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    site_detail_api_v1_operations_sites__site_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                site_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finance_today_api_v1_finance_today_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinanceToday"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ar_aging_api_v1_finance_ar_aging_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArAging"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finance_kpis_api_v1_finance_kpis_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinanceKpis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_trend_api_v1_finance_monthly_trend_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthRevenue"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clinical_summary_api_v1_clinical_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    credentials_expiring_api_v1_clinical_credentials_expiring_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialExpiring"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    people_summary_api_v1_people_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_positions_by_site_api_v1_people_open_positions_by_site_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenPositionBySite"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scorecards_api_v1_scorecards_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorecardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_alerts_api_v1_alerts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_recent_uploads_api_v1_uploads_get: {
        parameters: {
            query?: {
                /** @description Only return rows with id > since_id */
                since_id?: number | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stage_upload_api_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_stage_upload_api_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAcceptedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_census_api_v1_entries_daily_census_get: {
        parameters: {
            query?: {
                /** @description Defaults to today (server time, UTC) */
                date?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_daily_census_api_v1_entries_daily_census_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyCensusBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_monthly_finance_api_v1_entries_monthly_finance_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyFinanceRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_monthly_finance_api_v1_entries_monthly_finance_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlyFinanceBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyFinanceRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_clinical_api_v1_entries_weekly_clinical_get: {
        parameters: {
            query?: {
                week_ending?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyClinicalRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_weekly_clinical_api_v1_entries_weekly_clinical_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyClinicalBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyClinicalRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weekly_hr_api_v1_entries_weekly_hr_get: {
        parameters: {
            query?: {
                week_ending?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyHrOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_weekly_hr_api_v1_entries_weekly_hr_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyHrIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyHrOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_census_portal_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalLoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_with_today_api_v1_census_portal_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                census_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalLoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_census_portal_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                census_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_daily_census_api_v1_census_portal_daily_census_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                census_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalCensusBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalCensusOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
